/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import metodos.Riemman;
import metodos.Simpson13;
import metodos.Simpson38;
import metodos.Trapecio;

/**
 *
 * @author mez29
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        fx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Riemann = new javax.swing.JButton();
        Trapecio = new javax.swing.JButton();
        Simpson1_3 = new javax.swing.JButton();
        Simpson3_8 = new javax.swing.JButton();
        jTextField2_Reimann = new javax.swing.JTextField();
        jTextField3_Trapecio = new javax.swing.JTextField();
        jTextField4_Simpson1_3 = new javax.swing.JTextField();
        jTextField5_Simpson3_8 = new javax.swing.JTextField();
        jTextField_Particiones = new javax.swing.JTextField();
        b_salir = new javax.swing.JButton();
        b_nuevoIntegracion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 204, 204)));
        jPanel1.setLayout(null);

        b.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        b.setText("b=");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(60, 90, 50, 30);

        a.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        a.setText("a=");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        jPanel1.add(a);
        a.setBounds(40, 170, 50, 30);

        fx.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        fx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fxActionPerformed(evt);
            }
        });
        jPanel1.add(fx);
        fx.setBounds(60, 130, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/integral-mathematical-sign2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 110, 50, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("dx");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 130, 20, 20);

        jLabel3.setText("Numero de particiones");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 210, 130, 14);

        Riemann.setText("Reiman");
        Riemann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiemannActionPerformed(evt);
            }
        });
        jPanel1.add(Riemann);
        Riemann.setBounds(20, 260, 110, 23);

        Trapecio.setText("Trapecio");
        Trapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrapecioActionPerformed(evt);
            }
        });
        jPanel1.add(Trapecio);
        Trapecio.setBounds(20, 300, 110, 23);

        Simpson1_3.setText("Simpson 1/3");
        Simpson1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpson1_3ActionPerformed(evt);
            }
        });
        jPanel1.add(Simpson1_3);
        Simpson1_3.setBounds(20, 340, 110, 23);

        Simpson3_8.setText("Simpson 3/8");
        Simpson3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpson3_8ActionPerformed(evt);
            }
        });
        jPanel1.add(Simpson3_8);
        Simpson3_8.setBounds(20, 380, 110, 23);

        jTextField2_Reimann.setEditable(false);
        jPanel1.add(jTextField2_Reimann);
        jTextField2_Reimann.setBounds(140, 250, 160, 30);

        jTextField3_Trapecio.setEditable(false);
        jPanel1.add(jTextField3_Trapecio);
        jTextField3_Trapecio.setBounds(140, 290, 160, 30);

        jTextField4_Simpson1_3.setEditable(false);
        jPanel1.add(jTextField4_Simpson1_3);
        jTextField4_Simpson1_3.setBounds(140, 330, 160, 30);

        jTextField5_Simpson3_8.setEditable(false);
        jPanel1.add(jTextField5_Simpson3_8);
        jTextField5_Simpson3_8.setBounds(140, 370, 160, 30);
        jPanel1.add(jTextField_Particiones);
        jTextField_Particiones.setBounds(160, 200, 80, 30);

        b_salir.setText("Salir");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });
        jPanel1.add(b_salir);
        b_salir.setBounds(240, 450, 53, 23);

        b_nuevoIntegracion.setText("Nueva Integracion");
        b_nuevoIntegracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nuevoIntegracionActionPerformed(evt);
            }
        });
        jPanel1.add(b_nuevoIntegracion);
        b_nuevoIntegracion.setBounds(80, 30, 160, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void TrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrapecioActionPerformed
        // TODO add your handling code here:
        String funcion = fx.getText();
        String a1=a.getText();
        String b1=b.getText();
        String n =jTextField_Particiones.getText();
        
        Trapecio obj = new Trapecio();
        jTextField3_Trapecio.setText(obj.metodoTrapecio(a1, b1, funcion, n));
        
    }//GEN-LAST:event_TrapecioActionPerformed

    private void fxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fxActionPerformed

    private void RiemannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiemannActionPerformed
        String funcion=fx.getText();
        String a1 = a.getText();
        String b1 = b.getText();
        String n = jTextField_Particiones.getText();
        
        Riemman obj = new Riemman();
        jTextField2_Reimann.setText(obj.metodoRiemman(a1, b1, funcion, n));
        
    }//GEN-LAST:event_RiemannActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_nuevoIntegracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nuevoIntegracionActionPerformed
        // TODO add your handling code here:
        a.setText("");
        b.setText("");
        fx.setText("");
        jTextField2_Reimann.setText("");
        jTextField3_Trapecio.setText("");
        jTextField4_Simpson1_3.setText("");
        jTextField5_Simpson3_8.setText("");
        jTextField_Particiones.setText("");
    }//GEN-LAST:event_b_nuevoIntegracionActionPerformed

    private void Simpson1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpson1_3ActionPerformed
        String funcion=fx.getText();
        String a1 = a.getText();
        String b1 = b.getText();
        String n = jTextField_Particiones.getText();
        
        Simpson13 obj = new Simpson13();
        jTextField4_Simpson1_3.setText(obj.metodoSimpson13(a1, b1, funcion, n));
        
    }//GEN-LAST:event_Simpson1_3ActionPerformed

    private void Simpson3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpson3_8ActionPerformed
        String funcion=fx.getText();
        String a1 = a.getText();
        String b1 = b.getText();
        String n = jTextField_Particiones.getText();
        
        Simpson38 obj = new Simpson38();
        jTextField5_Simpson3_8.setText(obj.metodoSimpson38(a1, b1, funcion, n));
        
    }//GEN-LAST:event_Simpson3_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Riemann;
    private javax.swing.JButton Simpson1_3;
    private javax.swing.JButton Simpson3_8;
    private javax.swing.JButton Trapecio;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JButton b_nuevoIntegracion;
    private javax.swing.JButton b_salir;
    private javax.swing.JTextField fx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2_Reimann;
    private javax.swing.JTextField jTextField3_Trapecio;
    private javax.swing.JTextField jTextField4_Simpson1_3;
    private javax.swing.JTextField jTextField5_Simpson3_8;
    private javax.swing.JTextField jTextField_Particiones;
    // End of variables declaration//GEN-END:variables
}
