
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mez29
 */
public class Gauss extends javax.swing.JFrame {
    int n;
    DefaultTableModel modelo = new DefaultTableModel();
    Boolean ban = false;
    

    public int getN() {
        return n;
    }

    public void setN(int n) {
        this.n = n;
    }
    
    

    /**
     * Creates new form Gauss
     */
    public Gauss() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNumIn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Metodo Gauss-Jordan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Yu Gothic UI Light", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setText("Numero de incognitas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 190, 130, 30);
        jPanel1.add(jTextNumIn);
        jTextNumIn.setBounds(140, 190, 60, 30);

        jButton1.setText("Generar matriz aumentada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 190, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "x"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 360, 110);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(390, 70, 900, 380);

        jButton2.setText("Limpiar");
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 490, 90, 23);

        jButton3.setText("Resolver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 390, 120, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            this.setN(Integer.parseInt(jTextNumIn.getText()));
            n = this.getN();
            
            if(n<=1){
                throw new Exception ("Ingresaste un número invalido");
                
            }
            
            Object columna[] = new Object [n+1];
            for(int i=0; i<n+1; i++){
                if (i<n) {
                    columna[i] = "x" + (i + 1);
                } else{
                    columna[i] = "d";
                }
            }
            modelo = new DefaultTableModel(columna, n);
            jTable1.setModel(modelo);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            int n = this.getN();
            double m[][] = new double [n][n];
            double r [] = new double [n];
            
            for (int i = 0; i< n; i++){
                for (int j = 0; j< n; j++){
                    m[i][j]= Double.parseDouble(String.valueOf(jTable1.getValueAt(i, j)));
                }
                r[i] = Double.parseDouble(String.valueOf(jTable1.getValueAt(i, n)));
            }
            
            r = this.resolver(m,r);
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error en la lectura de datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gauss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextNumIn;
    // End of variables declaration//GEN-END:variables

    private double[] resolver(double[][] m, double[] r) {
        int n = this.getN();
        for(int i=0; i<n; i++){
            double d, c = 0;
            d = m[i][i];
            jTextArea1.append(Double.toString(1/d)+ " Fila"+(i+1) + "\n");
            for(int j =0; j<n; j++){
                m[i][j]= ((m[i][j])/d);
            }
            r[i] = ((r[i])/d);
            
            
            for (int j = 0; j<n; j++){
                for (int k=0; k< n; k++){
                    jTextArea1.append(Double.toString(m[j][k])+"\t");
                }
                jTextArea1.append("|\t"+ Double.toString(r[j])+"\n");
           }
            jTextArea1.append("\n\n");
            
         for (int x = 0; x<n; x++){
             if(i !=x){
                 c= m[x][i];
                 jTextArea1.append("-"+ Double.toString(c)+" Fila" + (i+1)+ "+ Fila" + (x+1)+ "\n");
                 for (int y=0; y <n; y++){
                     m[x][y] = m[x][y] -c * m [i][y];
                 }
                 r[x]= r[x]-c*r[i];
                 
                 for(int j= 0; j<n; j++){
                     for (int k=0; k<n; k++){
                         jTextArea1.append(Double.toString(m[j][k])+ "\t");
                     }
                     jTextArea1.append("|\t"+ Double.toString(r[j])+"\n");
                 }
                  jTextArea1.append("\n\n");
             }
             
         }
        }
        return r;
    }
}
